[book]
title = "Move Book 中文版"
authors = ["The Move China Contributors"]
language = "zh"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/move-dao/move-book-zh"
git-repository-icon = "fa-github"